version: "3"

services:
  cannons-game:
    build: .
    image: cannons-game
    container_name: cannons-game
    restart: unless-stopped
    # ports:
    #   - "8080:8080" # Only needed if Caddy is NOT in Docker
    networks:
      - proxy-net
    environment:
      - PORT=8080

networks:
  proxy-net:
    external: true